/** Autogenerated Main.cpp. */

#include <JuceHeader.h>
#include "includes.h"

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::Nakof_Vibrato<1>, wrap::illegal_poly<project::Nakof_Vibrato<1>>>();
		registerPolyNode<project::Vibrato<1>, wrap::illegal_poly<project::Vibrato<1>>>();
	}
};
}

scriptnode::dll::FactoryBase* hise::FrontendHostFactory::createStaticFactory()
{
	return new project::Factory();
}

